import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("ships the PWA and offline route dataset", async () => {
  const [manifest, serviceWorker, route] = await Promise.all([
    readFile(new URL("public/manifest.webmanifest", root), "utf8").then(JSON.parse),
    readFile(new URL("public/sw.js", root), "utf8"),
    readFile(new URL("public/data/swcp-route.json", root), "utf8").then(JSON.parse),
  ]);
  assert.equal(manifest.display, "standalone");
  assert.doesNotMatch(serviceWorker, /tile\.openstreetmap\.org/);
  assert.match(serviceWorker, /\/data\/swcp-route\.json/);
  assert.match(serviceWorker, /PREPARE_OFFLINE/);
  assert.match(serviceWorker, /navigationResponse/);
  assert.match(serviceWorker, /shellAssetsFromHtml/);
  assert.match(serviceWorker, /cacheAssetGraph/);
  assert.match(serviceWorker, /importedAssetsFromText/);
  assert.match(serviceWorker, /READY_MARKER/);
  assert.match(serviceWorker, /hasCachedShell/);
  assert.match(serviceWorker, /if \(!ready\) throw new Error\("The complete app shell could not be cached"\)/);
  assert.doesNotMatch(serviceWorker, /return cached \?\? network/);
  assert.ok(route.points.filter(Boolean).length > 4600);
  assert.ok(route.officialDistanceKm > 105 && route.officialDistanceKm < 106);
  assert.match(route.geometrySource, /Supplied South West Coast Path GPX/);
  assert.match(route.elevationSource, /Supplied GPX elevation/);
  assert.deepEqual(route.checkpoints.map((point) => point.name), ["Mousehole", "Penzance", "Porthleven", "Lizard Point", "Coverack", "Helford", "Falmouth"]);
  assert.ok(route.checkpoints[1].distanceKm > 5 && route.checkpoints[1].distanceKm < 6);
});

test("includes the requested offline-first features", async () => {
  const app = await readFile(new URL("app/components/CoastPathApp.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const database = await readFile(new URL("app/lib/db.ts", root), "utf8");
  const days = await readFile(new URL("app/lib/days.ts", root), "utf8");
  const planning = await readFile(new URL("app/lib/planning.ts", root), "utf8");
  const matching = await readFile(new URL("app/lib/route.ts", root), "utf8");
  assert.match(database, /IndexedDB|Dexie|coastline-swcp/i);
  assert.match(database, /bundledRouteData/);
  assert.match(database, /normalizeDayOrders/);
  assert.match(days, /order: index \+ 1/);
  assert.match(app, /watchPosition/);
  assert.match(app, /Simulate GPS/);
  assert.match(app, /simulatedGpsNearCheckpoint/);
  assert.match(app, /<strong>Track GPS<\/strong>/);
  assert.match(app, /gps\.latitude\.toFixed\(6\)/);
  assert.match(app, /gps\.longitude\.toFixed\(6\)/);
  assert.match(app, /Accuracy ±\{Math\.round\(gps\.accuracy\)\} metres/);
  assert.match(app, /Tap the location button at the top right to start GPS/);
  assert.match(app, /setTrackGps\(false\)/);
  assert.match(styles, /\.gps-coordinate-display/);
  assert.match(app, /ReferenceDot/);
  assert.match(app, /You are here/);
  assert.match(app, /Previous walking day/);
  assert.match(app, /Next walking day/);
  assert.match(app, /dayIdForDate\(loadedDays, localDateKey\(\)\)/);
  assert.match(app, /id="plan-start-date"/);
  assert.match(app, /savePlanStartDate\(value\)/);
  assert.match(app, /DndContext/);
  assert.match(app, /SortableContext/);
  assert.match(app, /reorderWalkingDays/);
  assert.match(app, /Break day/);
  assert.match(app, /toggleBreakAfter/);
  assert.doesNotMatch(app, /editor\.day\.date/);
  assert.match(app, /window\.setTimeout\(\(\) => setNotice\(""\), 4000\)/);
  assert.match(app, /window\.clearTimeout\(timeout\)/);
  assert.match(app, /withClientTimeout\(navigator\.serviceWorker\.register\("\/sw\.js"\), 8000\)/);
  assert.match(app, /handleOnline = \(\) => \{ setOnline\(true\); refreshOfflineState\(\); \}/);
  assert.match(app, /navigator\.serviceWorker\.controller \? "ready" : "limited"/);
  assert.match(app, /Start where the previous day ended/);
  assert.match(app, /<label>Start point<select/);
  assert.match(app, /<label>End point<select/);
  assert.doesNotMatch(app, /Start location name/);
  assert.doesNotMatch(app, /End location name/);
  assert.match(app, /No walking days planned/);
  assert.doesNotMatch(app, /Match to trail/);
  assert.doesNotMatch(app, /CoordinateMatcher/);
  assert.match(app, /nearestRoutePosition\(route, lng, lat\)/);
  assert.match(app, /Open \$\{selectedDay\.startName\} in OS Maps/);
  assert.match(app, /osMapsUrl\(startLocation\)/);
  assert.match(app, /osMapsUrl\(location\)/);
  assert.doesNotMatch(app, /Google Maps/);
  assert.doesNotMatch(app, /googleMapsUrl/);
  assert.doesNotMatch(app, /Verify start point in Google Maps/);
  assert.doesNotMatch(app, /Verify end point in Google Maps/);
  assert.match(app, /<h1>Locations<\/h1>/);
  assert.match(app, /label="Locations"/);
  assert.match(app, /tab === "locations"/);
  assert.doesNotMatch(app, /tab === "data"/);
  assert.doesNotMatch(app, /label="Route"/);
  assert.doesNotMatch(app, /Offline trail data/);
  assert.match(app, /Match and save/);
  assert.match(app, /window\.confirm\(warning\)/);
  assert.match(app, /prepareRouteImport\(route, imported, days\)/);
  assert.match(app, /replaceRouteAndDays\(prepared\.route, prepared\.days\)/);
  assert.match(app, /GPX import cancelled\. Nothing was changed\./);
  assert.doesNotMatch(app, /Fine-tune start/);
  assert.doesNotMatch(app, /Fine-tune end/);
  assert.match(app, /AreaChart/);
  assert.match(app, /<h2>\{selectedDay\.startName\} <ArrowRight \/> \{selectedDay\.endName\}<\/h2>/);
  assert.match(app, /profile-day-line/);
  assert.match(app, /<time dateTime=\{selectedDay\.date \|\| undefined\}>\{formatDate\(selectedDay\.date\)\}<\/time>/);
  assert.doesNotMatch(app, /chart-note/);
  assert.doesNotMatch(app, /The bundled profile uses elevation/);
  assert.doesNotMatch(app, /<section className="hero-row">/);
  assert.doesNotMatch(app, /<Navigation size=\{14\} \/> Trail tracker/);
  assert.match(app, /profile-day-navigation/);
  assert.match(app, /<Mountain \/> \{highestPoint\.toLocaleString\(\)\} m/);
  assert.match(app, /progress-details/);
  assert.doesNotMatch(app, /Use your iPhone location to calculate progress/);
  assert.doesNotMatch(app, /<Metric /);
  assert.doesNotMatch(app, /summary-stats/);
  assert.match(app, /Route data &amp; GPX/);
  assert.doesNotMatch(app, /CoastMap/);
  assert.match(app, /landscape-profile-ready/);
  assert.match(styles, /orientation: landscape/);
  assert.match(styles, /max-height: 500px/);
  assert.match(styles, /main-content > :not\(\.profile-card\)/);
  assert.match(styles, /height: 100dvh/);
  assert.match(planning, /totalPlannedDistanceKm/);
  assert.match(matching, /nearestRoutePosition/);
});
